import {chromium} from "playwright";
const browser=await chromium.launch({headless:true,args:["--use-gl=angle","--use-angle=swiftshader","--enable-webgl"]});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on("pageerror",e=>errors.push(String(e)));
const pixel=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wps7fQAAAAASUVORK5CYII=","base64");
await page.route("**/*",async route=>{
 const url=route.request().url();
 if(url.startsWith("http://127.0.0.1:4173/"))return route.continue();
 if(/\.(?:png|jpg|jpeg)(?:\?|$)/.test(url)||/MapServer\/tile/.test(url))return route.fulfill({status:200,contentType:"image/png",body:pixel,headers:{"access-control-allow-origin":"*"}});
 return route.abort();
});
await page.goto("http://127.0.0.1:4173/",{waitUntil:"domcontentloaded"});
await page.waitForFunction(()=>window.sarScan && document.querySelector("#modeMap [data-scan=spotlight]"),{timeout:20000});
const get=()=>page.evaluate(()=>window.sarScan.state());
let a=await get();if(a.mode!=="mosaic")throw Error("Default mode not mosaic");
await page.locator("#modeMap [data-scan=spotlight]").click();a=await get();if(a.mode!=="spotlight"||a.tx!==0||a.ty!==0)throw Error("Spotlight not aimed at stationary ground target");
await page.locator("#modeMap [data-scan=scansar]").click();await page.locator("#flightTime").evaluate(el=>{el.value="400";el.dispatchEvent(new Event("input",{bubbles:true}))});
a=await get();if(a.mode!=="scansar"||a.index<0||a.index>2)throw Error("ScanSAR mode or sub-swath missing");
await page.locator("#modeMap [data-scan=mosaic]").click();
await page.locator("#flightTime").evaluate(el=>{el.value="900";el.dispatchEvent(new Event("input",{bubbles:true}))});
a=await get();if(a.mode!=="mosaic"||a.pass!==2)throw Error("Multiple pass planner not reaching third strip");
let overlays=await page.locator("#scanPlan").count();if(overlays!==1)throw Error("Coverage overview missing");
await page.locator("#sarPointRun").click();
await page.waitForFunction(()=>document.querySelector("#sarPointResults")?.children.length===3||document.querySelector("#sarPointStatus")?.textContent?.includes("计算失败"),null,{timeout:90000});
let cards=await page.locator("#sarPointResults > div").count();if(cards!==3)throw Error("Actual IQ to BP mode comparison did not finish");
await page.waitForFunction(()=>document.querySelector("#radarAtlas #ra-status")?.textContent?.includes("计算完成"),null,{timeout:20000});
const atlas=await page.locator("#ra-options > button").count();if(atlas<4)throw Error("SAR/ISAR atlas taxonomy did not load");
await page.locator("#ra-cats [data-cat=motion]").click();await page.locator("#ra-options [data-tech=isar]").click();
if(!((await page.locator("#ra-name").textContent())||"").includes("ISAR"))throw Error("ISAR information panel is not linked");
await page.locator("#ra-cats [data-cat=measurement]").click();await page.locator("#ra-options [data-tech=polsar]").click();
await page.locator("#ra-B").evaluate(el=>{el.value="250";el.dispatchEvent(new Event("input",{bubbles:true}))});
await page.locator("#ra-run").click();
await page.waitForFunction(()=>document.querySelector("#radarAtlas #ra-status")?.textContent?.includes("计算完成")&&document.querySelector("#ra-Bval")?.textContent?.includes("250"),null,{timeout:20000});
if(!(await page.locator("#ra-res").textContent())?.includes("0.60"))throw Error("SAR/ISAR band-dependent range resolution did not update");
const images=await page.evaluate(()=>["ra-sar-img","ra-isar-img"].map(id=>{let c=document.getElementById(id);return {width:c.width,height:c.height,nonblank:c.getContext("2d").getImageData(Math.floor(c.width/2),Math.floor(c.height/2),1,1).data[3]>0}}));
if(images.some(v=>v.width<100||v.height<100||!v.nonblank))throw Error("SAR/ISAR coherent reconstruction canvas missing");
await page.waitForTimeout(350);
if(errors.length)throw Error(errors.join("\n"));
console.log(JSON.stringify({passed:true,tests:["mosaic","spotlight target lock","ScanSAR burst selector","three-pass mosaic","coverage plan","three IQ-to-BP point-target scenarios","SAR/ISAR atlas","measurement taxonomy","coherent dual reconstruction","bandwidth response","no JS exceptions"],latest:a.mode,pass:a.pass}));
await page.screenshot({path:"scan-smoke.png",fullPage:false});
await browser.close();